namespace _Games.CloudAPI.Model
{
    // Đợi làm xong rồi sửa.
    public enum ErrorCode
    {
        Unknown = 100,
        LEADERBOARD_UPDATE_INPUT_MISSING = 1000,
        LEADERBOARD_UPDATE_INPUT_UNDEFINE_TYPE = 1001,
        LEADERBOARD_UPDATE_INPUT_INVALID_VALUE = 1002,
        LEADERBOARD_UPDATE_INPUT_TOO_LARGE = 1003,
        LEADERBOARD_EMPTY = 1004,
        LEADERBOARD_NOT_FOUND_OPPONENT = 1005,
        TITLE_DATA_SESSION_NOT_CONFIGURED = 2000,
    }
}